"use client";

import { useEffect, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  generatePlansFromGroupAction,
  checkPlansExistAction,
  updatePlanGroupStatus,
} from "@/app/(student)/actions/planGroupActions";
import { 
  CACHE_STALE_TIME_DYNAMIC
} from "@/lib/constants/queryCache";
import { PlanScheduleView } from "@/app/(student)/plan/group/[id]/_components/PlanScheduleView";

type Step7ScheduleResultProps = {
  groupId: string;
  onComplete: () => void;
  isAdminContinueMode?: boolean;
};

export function Step7ScheduleResult({
  groupId,
  onComplete,
  isAdminContinueMode = false,
}: Step7ScheduleResultProps) {
  const queryClient = useQueryClient();
  const hasAutoGeneratedRef = useRef(false); // 자동 생성 중복 방지

  // 플랜 존재 여부 확인
  const { data: plansCheck, isLoading: isCheckingPlans } = useQuery({
    queryKey: ["plansExist", groupId],
    queryFn: () => checkPlansExistAction(groupId),
    staleTime: CACHE_STALE_TIME_DYNAMIC, // 1분간 캐시 유지
  });

  // 플랜 생성 뮤테이션
  const generatePlansMutation = useMutation({
    mutationFn: async () => {
      // 플랜 생성 전 상태를 "saved"로 변경 (필수: generatePlansFromGroupAction은 saved/active 상태만 허용)
      await updatePlanGroupStatus(groupId, "saved");
      return generatePlansFromGroupAction(groupId);
    },
    onSuccess: async () => {
      // 플랜 생성 후 DB 동기화를 위한 짧은 지연
      await new Promise((resolve) => setTimeout(resolve, 500));
      // 플랜 생성 후 관련 쿼리 무효화 및 즉시 refetch
      await queryClient.invalidateQueries({ queryKey: ["plansExist", groupId] });
      await queryClient.invalidateQueries({ queryKey: ["planSchedule", groupId] });
      // 즉시 refetch하여 최신 데이터 표시
      await queryClient.refetchQueries({ queryKey: ["plansExist", groupId] });
      await queryClient.refetchQueries({ queryKey: ["planSchedule", groupId] });
    },
  });

  // Step 7 진입 시 플랜이 없으면 자동 생성 (일반 모드만)
  useEffect(() => {
    // 관리자 continue 모드는 완료 버튼에서 continueCampStepsForAdmin 호출하므로 자동 생성 스킵
    if (isAdminContinueMode) {
      return;
    }

    // 일반 모드만 자동 생성
    // 플랜 확인이 완료되고, 플랜이 없고, 아직 자동 생성하지 않았고, 생성 중이 아닐 때만 실행
    if (
      !isCheckingPlans &&
      plansCheck &&
      !plansCheck.hasPlans &&
      !hasAutoGeneratedRef.current &&
      !generatePlansMutation.isPending &&
      !generatePlansMutation.isSuccess
    ) {
      console.log("[Step7ScheduleResult] 플랜이 없어 자동 생성 시작:", groupId);
      hasAutoGeneratedRef.current = true;
      generatePlansMutation.mutate();
    }
  }, [
    isCheckingPlans,
    plansCheck,
    groupId,
    isAdminContinueMode,
    generatePlansMutation.isPending,
    generatePlansMutation.isSuccess,
  ]);

  // 플랜 재생성 핸들러
  const handleRegenerate = () => {
    if (
      !confirm(
        "플랜을 재생성하시겠습니까? 기존 플랜이 삭제되고 새로 생성됩니다."
      )
    ) {
      return;
    }

    generatePlansMutation.mutate();
  };

  const isGenerating = generatePlansMutation.isPending;
  const isLoadingData = isCheckingPlans;
  const hasError = generatePlansMutation.error;

  if (isLoadingData || isGenerating) {
    return (
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-1">
          <h2 className="text-xl font-semibold text-gray-900">스케줄 결과</h2>
          <p className="text-sm text-gray-500">
            {isGenerating ? "플랜을 생성하는 중입니다..." : "생성된 학습 플랜을 확인할 수 있습니다."}
          </p>
        </div>
        <div className="flex flex-col gap-4 rounded-lg border border-gray-200 bg-gray-50 p-8 text-center">
          <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-gray-300 border-t-gray-900"></div>
          <p className="text-sm text-gray-500">
            {isGenerating ? "플랜 생성 중..." : "데이터를 불러오는 중..."}
          </p>
        </div>
      </div>
    );
  }

  if (hasError) {
    const errorMessage = 
      generatePlansMutation.error instanceof Error 
        ? `플랜 생성 실패: ${generatePlansMutation.error.message}`
        : typeof generatePlansMutation.error === 'object' && generatePlansMutation.error !== null && 'message' in generatePlansMutation.error
        ? String((generatePlansMutation.error as { message: unknown }).message)
        : "데이터를 불러오는 중 오류가 발생했습니다.";

    return (
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-1">
          <h2 className="text-xl font-semibold text-gray-900">스케줄 결과</h2>
          <p className="text-sm text-gray-500">
            생성된 학습 플랜을 확인할 수 있습니다.
          </p>
        </div>
        <div className="flex flex-col gap-2 rounded-lg border border-red-200 bg-red-50 p-4">
          <h3 className="text-sm font-semibold text-red-800">오류</h3>
          <p className="text-sm text-red-700">{errorMessage}</p>
        </div>
      </div>
    );
  }

  // 플랜이 없을 때 에러 표시 (자동 생성 시도 후에도 실패한 경우)
  // 자동 생성이 진행 중이거나 성공한 경우는 로딩 화면으로 처리되므로 여기서는 에러만 표시
  if (
    !isLoadingData &&
    !isGenerating &&
    plansCheck &&
    !plansCheck.hasPlans &&
    (generatePlansMutation.isError || hasAutoGeneratedRef.current)
  ) {
    return (
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-1">
          <h2 className="text-xl font-semibold text-gray-900">스케줄 결과</h2>
          <p className="text-sm text-gray-500">
            생성된 학습 플랜을 확인할 수 있습니다.
          </p>
        </div>
        <div className="flex flex-col gap-3 rounded-lg border border-red-200 bg-red-50 p-4">
          <h3 className="text-sm font-semibold text-red-800">오류</h3>
          <p className="text-sm text-red-700">
            플랜 생성에 실패했습니다. 플랜 재생성 버튼을 클릭하여 다시 시도해주세요.
          </p>
          <button
            type="button"
            onClick={handleRegenerate}
            disabled={generatePlansMutation.isPending}
            className="inline-flex items-center justify-center rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:bg-red-400"
          >
            {generatePlansMutation.isPending ? "재생성 중..." : "플랜 재생성"}
          </button>
        </div>
      </div>
    );
  }

  // 플랜이 있을 때 스케줄 결과 표시
  // PlanScheduleView가 자체적으로 데이터를 페칭하므로 조건부 렌더링만
  if (!plansCheck?.hasPlans && !generatePlansMutation.isSuccess) {
    return null;
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <h2 className="text-xl font-semibold text-gray-900">스케줄 결과</h2>
          <p className="text-sm text-gray-500">
            생성된 학습 플랜을 확인할 수 있습니다.
          </p>
        </div>
        <button
          type="button"
          onClick={handleRegenerate}
          disabled={generatePlansMutation.isPending}
          className="inline-flex items-center justify-center rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-indigo-400"
        >
          {generatePlansMutation.isPending ? "재생성 중..." : "플랜 재생성"}
        </button>
      </div>

      {/* PlanScheduleView가 자체적으로 데이터를 페칭하고 탭 전환 버튼을 제공 */}
      <PlanScheduleView groupId={groupId} />
    </div>
  );
}

